# Generated by Django 4.2.1 on 2023-06-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery_capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bc', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Biks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pover', models.IntegerField(verbose_name='ID_p')),
                ('id_bc', models.IntegerField(verbose_name='ID_bc')),
                ('name_bike', models.CharField(max_length=50, verbose_name='Название')),
                ('description_bike', models.TextField(verbose_name='Описание')),
                ('photo', models.CharField(max_length=250, verbose_name='Каринка')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_p', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
    ]
