# Generated by Django 4.2.1 on 2023-06-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_basket', models.CharField(max_length=25, verbose_name='COOKIE_ID_basket')),
                ('id_bike', models.IntegerField(verbose_name='ID_bike')),
                ('kolvo', models.IntegerField(verbose_name='Количество')),
            ],
        ),
    ]
