# Generated by Django 4.2.1 on 2023-07-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiya', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('imya', models.CharField(max_length=50, verbose_name='Имя')),
                ('adres', models.TextField(verbose_name='Адрес')),
                ('login_cust', models.CharField(max_length=50, verbose_name='Логин')),
                ('parol', models.CharField(max_length=50, verbose_name='Пароль')),
                ('mail', models.CharField(max_length=50, verbose_name='Почта')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('podpiska', models.IntegerField(verbose_name='Подписка')),
            ],
        ),
    ]
