# Generated by Django 4.2.1 on 2023-07-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.CharField(max_length=25, verbose_name='Номер заказа')),
                ('date_order', models.DateField(verbose_name='Дата заказа')),
                ('id_cust', models.IntegerField(max_length=50, verbose_name='IDПокупателя')),
                ('discount', models.IntegerField(verbose_name='ВариантДоставки')),
            ],
        ),
    ]
