# Generated by Django 4.2.1 on 2023-07-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.CharField(max_length=25, verbose_name='Номер заказа')),
                ('id_bike', models.IntegerField(max_length=50, verbose_name='IDБайка')),
                ('kolvo', models.IntegerField(verbose_name='Количество')),
            ],
        ),
    ]
